version: "3.2"
volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    ports:
      - "9900:8080"
      - "9943:8443"
    environment:
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
    volumes:
      - type: bind
        source: ./ssl/tls.crt
        target: /etc/x509/https/tls.crt
      - type: bind
        source: ./ssl/tls.key
        target: /etc/x509/https/tls.key
    depends_on:
      - postgres