//import com.medisec.hospitalservice.firewall.FirewallLog;
//import com.medisec.hospitalservice.firewall.Logs;
//import com.medisec.hospitalservice.firewall.LogType;
//import java.util.Arrays;
//
//rule "More than one failed login attempt with the same username"
//    when
//        log : FirewallLog(getPathResource() == "login", getStatus() == 400)
//    then
//        System.out.println("More than one failed login attempt with the same username");
//end
//
//rule "Attempt to login to an account that has not been active for 90 days"
//    when
//        log : FirewallLog(getPathResource() == "login", $username: getUsername())
//        logs: Logs(getInactiveAccounts() contains $username)
//    then
//        System.out.println("Attempt to login to an account that has not been active for 90 days");
//end
//
//rule "Log type ERROR"
//    when
//        log : FirewallLog(getType() == LogType.ERROR)
//    then
//        System.out.println("Log type ERROR");
//end
//
//rule "Login or attempt to login from an IP address that is on the list of malicious IP addresses"
//    when
//        log : FirewallLog(getPathResource() == "login", $sourceIp: getSourceIp())
//        logs: Logs(getMaliciousIps() contains $sourceIp)
//    then
//        System.out.println("Login or attempt to login from an IP address that is on the list of malicious IP addresses");
//end
//
//
//rule "Appearance of a log containing an source IP address from the list of malicious IP addresses"
//    when
//         log : FirewallLog($sourceIp: getSourceIp())
//         logs: Logs(getMaliciousIps() contains $sourceIp)
//    then
//        System.out.println("Appearance of a log containing an IP address from the list of malicious IP addresses");
//end
//
//rule "Appearance of a log containing an destination IP address from the list of malicious IP addresses"
//    when
//         log : FirewallLog($destIp: getDestIp())
//         logs: Logs(getMaliciousIps() contains $destIp)
//    then
//        System.out.println("Appearance of a log containing an IP address from the list of malicious IP addresses");
//end
//
//rule "30 or more unsuccessful login attempts are registered from the same IP address within 24 hours - add that IP address to the list of malicious IP addresses"
//    when
//        log : FirewallLog(getPathResource() == "login", status == 400)
//    then
//        System.out.println("Failed login!");
//end
//
//rule "Enable detection of overly frequent requests (more than 50 within 60 seconds)"
//    when
//        logs: Logs();
//        Number(intValue >= 0) from accumulate(
//                 $log : FirewallLog(
//                    getPathResource() == "login",
//                    status == 400),
//                 count( $log ))
//    then
//        System.out.println("Failed login!");
//end
