import com.medisec.hospitalservice.logs.medical_record_log.MedicalRecordLog;
import com.medisec.hospitalservice.logs.medical_record_log.Severity;
import com.medisec.hospitalservice.logs.medical_record_log.MedicalRecordAlarm;
import com.medisec.hospitalservice.alarms.medical_record_alarm.MedicalRecordAlarmService;

import java.util.UUID;
import java.util.Date;


global MedicalRecordAlarmService service;
rule "Heart beat over 110"
    when
        medicalRecord : MedicalRecordLog($patientId: patientId, heartBeat > 110 )
    then
        System.out.println(String.format("Patient {%s} - Heart beat over 110", $patientId));
        insert(new MedicalRecordAlarm(
                               UUID.randomUUID().toString(),
                               1L,
                               new Date(),
                               Severity.LOW,
                               "Event source",
                               1001L,
                               String.format("Patient {%s} - Heart beat over 110", $patientId),
                               1L,
                               false
                       ));
end

rule "Insert alaram to db"
    when
        alarm: MedicalRecordAlarm(persisted == false)
    then
        modify(alarm) {
            setPersisted(true)
        };
        service.save(alarm);
end

rule "Heart beat below 75"
    when
        medicalRecord : MedicalRecordLog($patientId: patientId, heartBeat < 75 )
    then
        System.out.println(String.format("Patient {%s} - Heart beat below 75", $patientId));
end

rule "Systolic blood pressure is above 145"
    when
        medicalRecord : MedicalRecordLog($patientId: patientId, getSystolicBloodPressure() > 145  )
    then
        System.out.println(String.format("Patient {%s} - Systolic body pressure is above 145", $patientId));
end

rule "Systolic blood pressure is below 110"
    when
        medicalRecord : MedicalRecordLog($patientId: patientId, getSystolicBloodPressure() < 110);
    then
        System.out.println(String.format("Patient {%s} - Systolic body pressure is below 110", $patientId));
end

rule "Diastolic blood pressure is below 65"
    when
        medicalRecord : MedicalRecordLog($patientId: patientId, getDiastolicBloodPressure() < 65  )
    then
        System.out.println(String.format("Patient {%s} - Diastolic body pressure is below 65", $patientId));
end

rule "Diastolic blood pressure is above 95"
    when
        medicalRecord : MedicalRecordLog($patientId: patientId, getDiastolicBloodPressure() > 95  )
    then
        System.out.println(String.format("Patient {%s} - Diastolic body pressure is above 95", $patientId));
end

