import com.medisec.hospitalservice.medical_record.MedicalRecord;
import static com.medisec.hospitalservice.medical_record.MedicalRecordAlarmGenerator.generateAlarm
import com.medisec.hospitalservice.medical_record.MedicalRecordAlarmGenerator
import com.medisec.hospitalservice.medical_record.Severity;


rule "Heart beat over 110"
    when
        medicalRecord : MedicalRecord($patientId: patientId, heartBeat > 70 )
    then
        System.out.println(String.format("Patient {%s} - Heart beat over 110", $patientId));
        MedicalRecordAlarmGenerator.generateAlarm(medicalRecord.getId(), Severity.LOW, "Neka poruka");
end

rule "Heart beat below 75"
    when
        medicalRecord : MedicalRecord($patientId: patientId, heartBeat < 75 )
    then
        System.out.println(String.format("Patient {%s} - Heart beat below 75", $patientId));
end

rule "Systolic blood pressure is above 145"
    when
        medicalRecord : MedicalRecord($patientId: patientId, getSystolicBloodPressure() > 145  )
    then
        System.out.println(String.format("Patient {%s} - Systolic body pressure is above 145", $patientId));
end

rule "Systolic blood pressure is below 110"
    when
        medicalRecord : MedicalRecord($patientId: patientId, getSystolicBloodPressure() < 110);
    then
        System.out.println(String.format("Patient {%s} - Systolic body pressure is below 110", $patientId));
end

rule "Diastolic blood pressure is below 65"
    when
        medicalRecord : MedicalRecord($patientId: patientId, getDiastolicBloodPressure() < 65  )
    then
        System.out.println(String.format("Patient {%s} - Diastolic body pressure is below 65", $patientId));
end

rule "Diastolic blood pressure is above 95"
    when
        medicalRecord : MedicalRecord($patientId: patientId, getDiastolicBloodPressure() > 95  )
    then
        System.out.println(String.format("Patient {%s} - Diastolic body pressure is above 95", $patientId));
end

